authors = ["Anthony D. Blaom <anthony.blaom@gmail.com>"]
name = "LearnAPI"
uuid = "92ad9a40-7767-427a-9ee6-6e577f1266cb"
version = "2.0.0"

[compat]
Preferences = "1.5.0"
julia = "1.10"

[deps]
Preferences = "21216c6a-2e73-6563-6e65-726566657250"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
